#!/usr/bin/env node
// `require` all files passed via command line
var relative = require('path').relative;
process.argv.slice(2).map(function (file) {
    require('./' + relative(__dirname, file));
});
